services:
  - type: web
    name: flume-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flume-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: BACKEND_CORS_ORIGINS
        sync: false
      - key: PYTHON_VERSION
        value: "3.12"
    autoDeploy: true

databases:
  - name: flume-db
    plan: free
